// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FileValue struct {
	Path                 string   `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Binary               []byte   `protobuf:"bytes,2,opt,name=binary,proto3" json:"binary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileValue) Reset()         { *m = FileValue{} }
func (m *FileValue) String() string { return proto.CompactTextString(m) }
func (*FileValue) ProtoMessage()    {}
func (*FileValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *FileValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileValue.Unmarshal(m, b)
}
func (m *FileValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileValue.Marshal(b, m, deterministic)
}
func (m *FileValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileValue.Merge(m, src)
}
func (m *FileValue) XXX_Size() int {
	return xxx_messageInfo_FileValue.Size(m)
}
func (m *FileValue) XXX_DiscardUnknown() {
	xxx_messageInfo_FileValue.DiscardUnknown(m)
}

var xxx_messageInfo_FileValue proto.InternalMessageInfo

func (m *FileValue) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *FileValue) GetBinary() []byte {
	if m != nil {
		return m.Binary
	}
	return nil
}

type FileBinary struct {
	Files                []*FileValue `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *FileBinary) Reset()         { *m = FileBinary{} }
func (m *FileBinary) String() string { return proto.CompactTextString(m) }
func (*FileBinary) ProtoMessage()    {}
func (*FileBinary) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *FileBinary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileBinary.Unmarshal(m, b)
}
func (m *FileBinary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileBinary.Marshal(b, m, deterministic)
}
func (m *FileBinary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileBinary.Merge(m, src)
}
func (m *FileBinary) XXX_Size() int {
	return xxx_messageInfo_FileBinary.Size(m)
}
func (m *FileBinary) XXX_DiscardUnknown() {
	xxx_messageInfo_FileBinary.DiscardUnknown(m)
}

var xxx_messageInfo_FileBinary proto.InternalMessageInfo

func (m *FileBinary) GetFiles() []*FileValue {
	if m != nil {
		return m.Files
	}
	return nil
}

type File struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Path                 string   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Size                 int64    `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *File) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_File.Unmarshal(m, b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_File.Marshal(b, m, deterministic)
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return xxx_messageInfo_File.Size(m)
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *File) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *File) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *File) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *File) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *File) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

// Our address book file is just one of these.
type FileList struct {
	File                 []*File  `protobuf:"bytes,1,rep,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileList) Reset()         { *m = FileList{} }
func (m *FileList) String() string { return proto.CompactTextString(m) }
func (*FileList) ProtoMessage()    {}
func (*FileList) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{5}
}

func (m *FileList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileList.Unmarshal(m, b)
}
func (m *FileList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileList.Marshal(b, m, deterministic)
}
func (m *FileList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileList.Merge(m, src)
}
func (m *FileList) XXX_Size() int {
	return xxx_messageInfo_FileList.Size(m)
}
func (m *FileList) XXX_DiscardUnknown() {
	xxx_messageInfo_FileList.DiscardUnknown(m)
}

var xxx_messageInfo_FileList proto.InternalMessageInfo

func (m *FileList) GetFile() []*File {
	if m != nil {
		return m.File
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "file.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "file.HelloReply")
	proto.RegisterType((*FileValue)(nil), "file.FileValue")
	proto.RegisterType((*FileBinary)(nil), "file.FileBinary")
	proto.RegisterType((*File)(nil), "file.File")
	proto.RegisterType((*FileList)(nil), "file.FileList")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 307 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x41, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0x50, 0xe0, 0x63, 0x3e, 0x82, 0x38, 0x07, 0xb3, 0xe1, 0x60, 0x9a, 0x4d, 0x34, 0x8d,
	0x07, 0x12, 0xe1, 0x60, 0xbc, 0x7a, 0x10, 0x0f, 0x9e, 0xd6, 0xc4, 0xfb, 0x12, 0x46, 0xd9, 0x64,
	0xa1, 0xb5, 0xbb, 0xc4, 0x94, 0x5f, 0x6f, 0x66, 0x5b, 0x5a, 0x4c, 0xbc, 0xbd, 0x79, 0xf3, 0xe6,
	0xcd, 0xcb, 0x0c, 0xc0, 0x87, 0xb1, 0x34, 0xcf, 0x8b, 0xcc, 0x67, 0x18, 0x33, 0x96, 0x12, 0xc6,
	0x2f, 0x64, 0x6d, 0xa6, 0xe8, 0xeb, 0x40, 0xce, 0x23, 0x42, 0x9c, 0x6b, 0xbf, 0x15, 0x51, 0x12,
	0xa5, 0x23, 0x15, 0xb0, 0xbc, 0x05, 0xa8, 0x35, 0xb9, 0x2d, 0x51, 0xc0, 0x70, 0x47, 0xce, 0xe9,
	0x4f, 0xaa, 0x45, 0xa7, 0x52, 0x3e, 0xc0, 0xe8, 0xd9, 0x58, 0x7a, 0xd7, 0xf6, 0x40, 0x7f, 0x19,
	0xe1, 0x15, 0x0c, 0xd6, 0x66, 0xaf, 0x8b, 0x52, 0x74, 0x93, 0x28, 0x1d, 0xab, 0xba, 0x92, 0x4b,
	0x00, 0x1e, 0x7c, 0x0a, 0x15, 0xde, 0x40, 0x9f, 0xa3, 0x39, 0x11, 0x25, 0xbd, 0xf4, 0xff, 0xe2,
	0x62, 0x1e, 0x42, 0x37, 0xce, 0xaa, 0xea, 0xca, 0x23, 0xc4, 0xcc, 0xf1, 0xa2, 0xbd, 0xde, 0x9d,
	0xc2, 0x04, 0x8c, 0x13, 0xe8, 0x9a, 0x4d, 0x58, 0xd2, 0x57, 0x5d, 0xb3, 0x69, 0xc2, 0xf4, 0xce,
	0xc2, 0x20, 0xc4, 0xbe, 0xcc, 0x49, 0xc4, 0x15, 0xc7, 0x98, 0x39, 0x67, 0x8e, 0x24, 0xfa, 0x49,
	0x94, 0xf6, 0x54, 0xc0, 0xcc, 0x6d, 0xb5, 0xdb, 0x8a, 0x41, 0xa5, 0x63, 0x2c, 0xef, 0xe0, 0x1f,
	0xef, 0x7e, 0x35, 0xce, 0xe3, 0x35, 0x84, 0x4b, 0xd6, 0x69, 0xa1, 0x4d, 0xab, 0x02, 0xbf, 0xf8,
	0x86, 0xe1, 0xaa, 0x20, 0xf2, 0x54, 0xe0, 0x23, 0x5c, 0xae, 0xc8, 0x2b, 0xda, 0x65, 0x9e, 0x9a,
	0x79, 0xac, 0x26, 0xce, 0xbf, 0x30, 0x9b, 0xb4, 0x2e, 0xac, 0x91, 0x1d, 0xbc, 0x87, 0xd1, 0x1b,
	0xed, 0x37, 0xcc, 0x38, 0x9c, 0xb6, 0xed, 0xea, 0x66, 0xb3, 0xe9, 0x2f, 0x93, 0xdc, 0x96, 0xb2,
	0xb3, 0x1e, 0x84, 0x3f, 0x2f, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x6b, 0x55, 0x7f, 0xf5,
	0x01, 0x00, 0x00,
}
